meta_product_name: "UNIDRAFT"
meta_title: "Unidraft - Vos créateurs de demain"
meta_description: "Votez pour vos croquis préférés et bénéficiez d'un bon d'achat de 10 euros !"
meta_image: "banner.png"                      # Une image dans votre dossier app/assets/images/
